replicaCount: 1
image:
  repository: arcayth/scrutis-worker
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

env:
  PORT: 3001

envFrom:
  - secretRef:
      name: better-auth-secret
  - secretRef:
      name: db-secret
  - secretRef:
      name: github-secret
