apiVersion: apps/v1
kind: Deployment

metadata:
  name: scrutis-web

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: scrutis-web

  template:
    metadata:
      labels:
        app: scrutis-web

    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
