replicaCount: 1
image:
  repository: arcayth/scrutis-web
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik

env:
  PORT: 3000

envFrom:
  - secretRef:
      name: better-auth-secret
  - secretRef:
      name: db-secret
  - secretRef:
      name: github-secret
